# Generated by Django 3.2.18 on 2023-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartBasket', '0002_auto_20230618_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(default='images/download.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
